Updated
microbiome/course_2022_FindingPheno pull request #2
Opened 2022-01-05 09:51 UTC by Begia

Simplified installation script and added info on Rtools installation for Windows users.

2022-01-05 11:39 UTC, ChouaibB requested changes

2022-01-05 11:39 UTC, ChouaibB commented on 02-start.Rmd
> +packages <- c("BiocManager", "ggplot2", "pheatmap", "stringr", "igraph", "ANCOMBC", "microbiome", "httpuv", "microbiomeDataSets", "mia", "caret", "ranger")
Thanks!
Could we please keep the following packages as well, they are needed at [other sections of the book](https://microbiome.github.io/course_2022_FindingPheno/) for the moment:
"miaViz", "dplyr", "gridExtra", "kableExtra", "knitr", "vegan", "ecodist"

2022-01-11 12:37 UTC, TuomasBorman requested changes
Check suggest of @ChouaibB and resolve conflicts

2022-01-11 18:55 UTC, ChouaibB commented
I will take care of this.

2022-01-11 19:36 UTC, merged